Add a version check to the build workflow

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -73,15 +73,24 @@ jobs:
           exit 1
         fi
 
-    - name: Smoke test
+    - name: Ensure version matches tag
       shell: bash
       run: |
-        if [ -f "artifact/cute.exe" ]; then
-          ./artifact/cute.exe version
-        elif [ -f "artifact/cute" ]; then
-          chmod +x ./artifact/cute
-          ./artifact/cute version
+        CUTE="artifact/cute"
+        if [ -F "artifact/cute.exe" ]; then
+          BIN="artifact/cute.exe"
         fi
+
+        chmod +x "$BIN"
+
+        version=$("$BIN" version | tr -d '\r')
+
+        if [[ "$version" != "${{ github.ref_name }}" ]]; then
+          echo "Error: binary version ($version) doesn't match tag version (${{ github.ref_name }})"
+          exit 1
+        fi
+
+        echo "Version check passed!"
 
     - name: Attest build provenance
       uses: actions/attest-build-provenance@v3
